services:
  kafka:
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://host.docker.internal:9093
    - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    - ALLOW_PLAINTEXT_LISTENER=yes
    image: bitnami/kafka:latest
    networks:
    - default
    ports:
    - 9092:9092
    - 9093:9093
    volumes: []
  zookeeper:
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    image: bitnami/zookeeper:latest
    networks:
    - default
    ports:
    - 2181:2181
    volumes: []
version: '3.8'
