version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://host.docker.internal:9093
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # Enable auto-creation of topics
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - zookeeper

  dummy-black-box-app:
    # calling 'docker-compose build' will rebuild this Dockerfile
    build: .
    ports:
      - '12345:12345'
    environment:
      TCP_HOST: '0.0.0.0'
      TCP_PORT: '12345'
      KAFKA_HOST: 'kafka:9092'
      KAFKA_TOPIC: 'DummyTopic'
    depends_on:
      - kafka
      - zookeeper
