name: Take Screenshot on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend Setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify the Python version you need

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Make sure you have a requirements.txt file

      - name: Start the backend server
        working-directory: ./backend
        run: python main.py &
        env:
          FLASK_ENV: development # or any other environment variables your backend needs

      # UI Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm install

      - name: Start the CRA development server
        working-directory: ./ui
        run: npm start &
        env:
          CI: true

      - name: Wait for servers to start
        run: sleep 20

      - name: Run Puppeteer to take screenshot
        working-directory: ./ui
        run: node screenshot.js

      - name: Commit screenshot
        working-directory: ./ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add screenshot.png
          git commit -m "Add screenshot [skip ci]"
          git push origin HEAD:${{ github.ref }}
